
# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 4096
CPU = 2

Vagrant.configure("2") do |config|
  config.vm.define "docker" do |docker|
    docker.vm.box = "geerlingguy/centos7"
    docker.vm.network "private_network", type: "dhcp"
    docker.vm.hostname = "docker"
    docker.vm.provider "virtualbox" do |v|
      v.name = "docker"
      v.memory = RAM
      v.cpus = CPU
    end
    docker.vm.provision :shell do |shell|
      shell.path = "install_docker.sh"
    end
  end
end