# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_version = "20190425.0.0"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
end
